[package]
name = "tokval"
version = "1.1.0"
edition = "2018"


[dependencies]
crossbeam = "0.8"
anyhow = "1.0"
num_cpus = "1.0"
regex = "1.5"
lazy_static = "1.4.0"
reqwest = {version = "0.11", features = ["blocking", "json"]}
tokio = "1"
