[package]
name = "tokval"
version = "2.2.1"
edition = "2018"


[dependencies]
crossbeam = "0.8"
anyhow = "1.0"
num_cpus = "1.0"
reqwest = {version = "0.11", features = ["blocking", "json"]}
tokio = "1"
clap = "~2.33"
log = "0.4"
simplelog = "^0.10.0"
